### ISSUE TITLE
Highlighting Valid Moves

### ISSUE THREAD

**Issue by Mohido** [Tariqo/Clean-Chess-Application#6]
Important Issue. (Game Can't be completed without it).
Highlighting valid moves should take the process state and checks what is the selected piece in the localState (GameState).  After checking what piece it was, it redirects to another function that does the piece algorithm for highlighting the valid moves of the piece. 
For Example, when the user click on a piece, now that piece is selected and the "selectedPiece" variable is set to refer to that piece. Then the highlighting function is called for that piece. 
Its definition: (PSt GameState) -> (PSt GameState)

Note: This is a huge issue that contains alot of functionality. For each piece there is a certien algorithm of movement. 
For example: Bishop moves by:
(x+1, y+1) or
(x-1, y+1) or
(x+1, y-1) or
(x-1, y-1)

Last Note: IMPLEMENT THE MOVEMENT HIGHLIGHTING ALGORITHM WITH TAIL RECURSIONO FOR MAXIMUM ALGORITHM EFFECIENCY AND PROCESSING EFFECIENCY!

**Comment by Tariqo** [comment]
Done
