### ISSUE TITLE
Checking the Move Validity

### ISSUE THREAD

**Issue by Mohido** [Tariqo/Clean-Chess-Application#7]
This is almost same functionality as highlighting the valid moves. This Function will be called right when dragging the piece is over. To check if the point that the piece is moving to is valid or not.  This function should be a redirect to smaller function (a function that is applied to the piece movement algorithm to check if the move is valid) after checking the current piece type.

Function definition: point2 (PSt GameState) -> (Bool, PSt GameState). 

The game state will contain the World matrix (Board matrix). So that is y it is passed to this function. Check if the current selected piece is legal to move to the point2 (tile coordinates).

**Comment by Tariqo** [comment]
Also done
