### ISSUE TITLE
Moving Pieces

### ISSUE THREAD

**Issue by Mohido** [Tariqo/Clean-Chess-Application#8]
Important Issue. (Game will not be completed without it)

We need to implement the dragging option to the game. The user can drag a piece from the board and change its position to another tile. Note things should be done on the WorldMatrix in the local state. And rendering the changes only (NOTE THE WHOLE BOARD!). Redraw the new tile and the previous tile. 

Note: Look at the Drawing Application in the book in chapter 5 (mouse handling section). That is the best resource for implementing such a feature!

**Comment by Tariqo** [comment]
Done
